export const Npcs = {
  Angler: "Angler",
  ArmsDealer: "Arms Dealer",
  Clothier: "Clothier",
  Cyborg: "Cyborg",
  Demolitionist: "Demolitionist",
  Dryad: "Dryad",
  DyeTrader: "Dye Trader",
  GoblinTinkerer: "Goblin Tinkerer",
  Golfer: "Golfer",
  Guide: "Guide",
  Mechanic: "Mechanic",
  Merchant: "Merchant",
  Nurse: "Nurse",
  Painter: "Painter",
  PartyGirl: "Party Girl",
  Pirate: "Pirate",
  SantaClaus: "Santa Claus",
  Steampunker: "Steampunker",
  Stylist: "Stylist",
  TaxCollector: "Tax Collector",
  Tavernkeep: "Tavernkeep",
  Truffle: "Truffle",
  WitchDoctor: "Witch Doctor",
  Wizard: "Wizard",
  Zoologist: "Zoologist",
  Princess: "Princess",
};
